force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Admin</fullName>
            </value>
            <value>
                <fullName>Salesforce Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce Integration</fullName>
            </value>
            <value>
                <fullName>Lightning Web Component</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Course_Cost__c.field-meta.xml
<CustomField>
    <fullName>Course_Cost__c</fullName>
    <label>Course Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Course_Duration__c.field-meta.xml
<CustomField>
    <fullName>Course_Duration__c</fullName>
    <label>Course Duration (in hours)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CourseCode__c.field-meta.xml
<CustomField>
    <fullName>CourseCode__c</fullName>
    <label>Course Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/ScheduledCourse__c.object-meta.xml
<CustomObject>
    <label>Scheduled Course</label>
    <nameField>
        <label>Scheduled Course ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduledCourse__c/fields/BookingUrl__c.field-meta.xml
<CustomField>
    <fullName>BookingUrl__c</fullName>
    <label>Booking Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Scheduled Courses</relationshipLabel>
    <relationshipName>Scheduled_Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/EnableRSVP__c.field-meta.xml
<CustomField>
    <fullName>EnableRSVP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable RSVP?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Max_Seat__c.field-meta.xml
<CustomField>
    <fullName>Max_Seat__c</fullName>
    <label>Max Seat</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Classroom Training</fullName>
            </value>
            <value>
                <fullName>Virtual Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Thumbnail__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail__c</fullName>
    <label>Thumbnail</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/TotalBooking__c.field-meta.xml
<CustomField>
    <fullName>TotalBooking__c</fullName>
    <label>Total Booking</label>
    <summaryFilterItems>
        <field>CourseBooking__c.Status__c</field>
        <operation>equals</operation>
        <value>Deposit Paid, Invoiced, Fully Paid</value>
    </summaryFilterItems>
    <summaryForeignKey>CourseBooking__c.Scheduled_Course__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Scheduled Courses</relationshipLabel>
    <relationshipName>Scheduled_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Training_Center__c.field-meta.xml
<CustomField>
    <fullName>Training_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Center</label>
    <referenceTo>TrainingCenter__c</referenceTo>
    <relationshipLabel>Scheduled Courses</relationshipLabel>
    <relationshipName>Scheduled_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduledCourse__c/fields/Zoom_Link__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Link__c</fullName>
    <label>Zoom Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

web/main/default/classes/CourseListService.cls
/**
 * @description       : 
 * @author            : Amit Singh - PantherSchools
 * @group             : 
 * @last modified on  : 06-13-2024
 * @last modified by  : Amit Singh - PantherSchools
**/
public without sharing class CourseListService {

    @AuraEnabled(cacheable=true)
    public static List<sObject> listCourses(){
        try {
            List<ScheduledCourse__c> courseList = [SELECT Id, Name, Course__c, Course__r.Course_Cost__c,Course__r.Category__c,
                            Course__r.CourseCode__c, Course__r.Course_Duration__c,
                            Start_Date_Time__c, End_Date_Time__c, Trainer__c,
                            EnableRSVP__c, BookingUrl__c, Thumbnail__c, 
                            Max_Seat__c, Mode__c, Status__c, Training_Center__c, Zoom_Link__c, TotalBooking__c 
                        FROM
                            ScheduledCourse__c 
                        WHERE
                            Status__c = 'Confirmed'
                    ];
            return courseList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}