force-app/main/default/objects/Product2/fields/QBExternalID__c.field-meta.xml
<CustomField>
    <fullName>QBExternalID__c</fullName>
    <externalId>true</externalId>
    <label>QB External ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Synced_With_Quickbooks__c.field-meta.xml
<CustomField>
    <fullName>Synced_With_Quickbooks__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced With Quickbooks</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/qb_Metadata__mdt/qb_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Quickbooks</label>
    <pluralLabel>Quickbooks</pluralLabel>
</CustomObject>

force-app/main/default/objects/qb_Metadata__mdt/fields/auth_url__c.field-meta.xml
<CustomField>
    <fullName>auth_url__c</fullName>
    <defaultValue>&quot;https://appcenter.intuit.com/connect/oauth2&quot;</defaultValue>
    <label>auth url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/qb_Metadata__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sandbox</fullName>
                <default>true</default>
                <label>Sandbox</label>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/qb_Metadata__mdt/fields/expires_in__c.field-meta.xml
<CustomField>
    <fullName>expires_in__c</fullName>
    <label>expires_in</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/qb_Metadata__mdt/fields/expires_in_time__c.field-meta.xml
<CustomField>
    <fullName>expires_in_time__c</fullName>
    <label>expires in time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/qb_Metadata__mdt/fields/minorversion__c.field-meta.xml
<CustomField>
    <fullName>minorversion__c</fullName>
    <label>minorversion</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/qb_Metadata__mdt/fields/Prod_Base_URL__c.field-meta.xml
<CustomField>
    <fullName>Prod_Base_URL__c</fullName>
    <defaultValue>&quot;https://quickbooks.api.intuit.com&quot;</defaultValue>
    <label>Production Base URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/qb_Metadata__mdt/fields/realmId__c.field-meta.xml
<CustomField>
    <fullName>realmId__c</fullName>
    <label>realmId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/qb_Metadata__mdt/fields/token_type__c.field-meta.xml
<CustomField>
    <fullName>token_type__c</fullName>
    <label>token_type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/qb_Metadata__mdt/fields/token_url__c.field-meta.xml
<CustomField>
    <fullName>token_url__c</fullName>
    <defaultValue>&quot;https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer&quot;</defaultValue>
    <label>token url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/QB_Items.cls
/**
 * @description       : 
 * @author            : Amit Singh - PantherSchools
 * @group             : 
 * @last modified on  : 04-20-2024
 * @last modified by  : Amit Singh - PantherSchools
**/
public with sharing class QB_Items {

    // QB_Items.testCreateItem();
    public static void testCreateItem(){
        List<Product2> products = [Select Id, Name FROM Product2 WHERE QBExternalID__c = null ];
        // System.CalloutException: You have uncommitted work pending. Please commit or rollback before calling out
        /**
         * Callout
         * Callout
         * Callout
         * Callout
         * DML - Works
         
         * Callout
         * DML
         * Callout - Fails System.CalloutException: You have uncommitted work pending. Please commit or rollback before calling out
         */
        for(Product2 prod: products){
            createItemInQB(prod); // Not a Best Practice, but will do for POC
        }
        update products;
    }
    
    public static Product2 createItemInQB(Product2 productRecord){
        /** Get the config from the Custom Metadta */
        List<qb_Metadata__mdt> configList = [SELECT Id, DeveloperName, MasterLabel,  Environment__c, Prod_Base_URL__c, Sanbdox_Base_URL__c,
                                        access_token__c, auth_url__c, expires_in__c, expires_in_time__c, minorversion__c, 
                                        realmId__c, refresh_token__c, token_type__c, token_url__c 
                                        FROM qb_Metadata__mdt 
                                        WHERE DeveloperName = 'QBToken' 
                                        LIMIT 1]; // Token Details Are Stored Here...
        if(configList?.size() > 0){
            qb_Metadata__mdt config = configList.get(0);
            
            String accessToken = config.access_token__c;
            
            Boolean isValid = PS_QBTokenUtil.isValid(config);
            Map<String, Object> fieldWithValuesMap;

            if(isValid == false){ // Token is Expired
                // Refresh the Token
                fieldWithValuesMap = PS_QBTokenUtil.refreshToken(config);
                accessToken = (String)fieldWithValuesMap.get('access_token__c'); // null/blank
            }

            HttpRequest httReq = new HttpRequest();
            httReq.setMethod('POST');
            httReq.setHeader('Content-Type', 'application/json');
            httReq.setHeader('Authorization', 'Bearer '+accessToken);
            httReq.setHeader('Accept', 'application/json');
            
            String endpoint = config.Prod_Base_URL__c+'/v3/company/'+config.realmId__c+'/item?minorversion='+config.minorversion__c;
            if(config.Environment__c.equals('Sandbox')){
                endpoint = config.Sanbdox_Base_URL__c+'/v3/company/'+config.realmId__c+'/item?minorversion='+config.minorversion__c;
            }
            
            httReq.setEndpoint(endpoint);
            
            String requestBody = '{'+
            '    "TrackQtyOnHand": false,'+
            '    "Name": "'+productRecord.Name+'",'+
            '    "QtyOnHand": 180,'+
            '    "IncomeAccountRef": {'+
            '        "name": "'+System.Label.IncomeAccountRefName+'",'+
            '        "value": "'+System.Label.IncomeAccountRefValue+'"'+
            '    },'+
            '    "AssetAccountRef": {'+
            '        "name": "'+System.Label.AssetAccountRefName+'",'+
            '        "value": "'+System.Label.AssetAccountRefValue+'"'+
            '    },'+
            '    "InvStartDate": "2025-01-01",'+
            '    "Type": "Service",'+
            '    "ExpenseAccountRef": {'+
            '        "name": "'+System.Label.ExpenseAccountRefName+'",'+
            '        "value": "'+System.Label.ExpenseAccountRefValue+'"'+
            '    }'+
            '}';
            
            httReq.setBody(requestBody);
            try {
                HttpResponse httpRes = (new Http()).send(httReq);
                if(httpRes.getStatusCode() == 200 || httpRes.getStatusCode() == 201 ){
                    Map<String,Object> responseMap = (Map<String,Object>)System.JSON.deserializeUntyped(httpRes.getBody());
                    Object item = responseMap.get('Item'); // {}
                    Map<String,Object> itemMap = (Map<String,Object>)item;
                    System.debug(' itemMap \n '+System.JSON.serializePretty(itemMap));
                    productRecord.QBExternalID__c = (String)itemMap.get('Id');
                    productRecord.Synced_With_Quickbooks__c = true; 

                    //upsert productRecord QBExternalID__c;
                    
                }else{
                    System.debug(' httpRes getBody '+httpRes.getBody());
                    System.debug(' httpRes getStatusCode '+httpRes.getStatusCode());
                }
            }catch(CalloutException ex) {
                System.debug('Exception Executed '+ex);
            }catch(Exception ex) {
                System.debug('Not Callout Exception Executed '+ex);
            }

            /**
             * Update the Custom metadata record with the latest values...
             */
            if(fieldWithValuesMap?.size() > 0){
                System.debug('Updating the Custom Metadata... ');
                String fullName = 'qb_Metadata.QBToken';
                String label    = 'QBToken';
                // Deploy/Update the Custom Metadata
                CreateUpdateMetadataUtils.createUpdateMetadata(fullName, label, fieldWithValuesMap);
            }
        }else{
            // Enhance this...
        }
        return productRecord;
    }
}