force-app/main/default/objects/OrderStatus__e/OrderStatus__e.object-meta.xml
<CustomObject>
    <label>Order Status</label>
    <pluralLabel>Order Status</pluralLabel>
</CustomObject>

force-app/main/default/objects/OrderStatus__e/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderStatus__e/fields/Total_Amount_in_USD__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_in_USD__c</fullName>
    <label>Total Amount ( in USD )</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrderTriggerHander.cls
/**
 * @description       : 
 * @author            : Amit Singh - PantherSchools
 * @group             : 
 * @last modified on  : 05-05-2024
 * @last modified by  : Amit Singh - PantherSchools
**/
public with sharing class OrderTriggerHander {
    public static void publishEvent(List<Order> newRecords){
        List<Order> orderToPublish = [SELECT OrderNumber FROM Order WHERE Id IN:newRecords ];
        List<OrderStatus__e> orderStatusList = new List<OrderStatus__e>();
        for(Order ord: orderToPublish ){
            OrderStatus__e orderStatus = new OrderStatus__e();
            orderStatus.Order_Number__c = ord.OrderNumber;
            orderStatus.Total_Amount_in_USD__c = 0.00;
            orderStatusList.add(orderStatus);
        }
        EventBus.publish(orderStatusList);
        // throw the Error
        Integer i = 10/0;
    }
}