project/dropbox/main/default/objects/DropBoxFile__c/DropBoxFile__c.object-meta.xml
<CustomObject>
    <label>DropBox File</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DropBox Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project/dropbox/main/default/objects/DropBoxFile__c/fields/Content_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Content_Document_Id__c</fullName>
    <label>Content Document Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

project/dropbox/main/default/objects/DropBoxFile__c/fields/Dropbox_File_Id__c.field-meta.xml
<CustomField>
    <fullName>Dropbox_File_Id__c</fullName>
    <description>The unique ID of the file in Dropbox</description>
    <externalId>true</externalId>
    <inlineHelpText>The unique ID of the file in Dropbox</inlineHelpText>
    <label>Dropbox File Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

project/dropbox/main/default/objects/DropBoxFile__c/fields/Dropbox_Path__c.field-meta.xml
<CustomField>
    <fullName>Dropbox_Path__c</fullName>
    <inlineHelpText>The full path of the file in Dropbox</inlineHelpText>
    <label>Dropbox Path</label>
    <type>Url</type>
</CustomField>

project/dropbox/main/default/objects/DropBoxFile__c/fields/File_Size__c.field-meta.xml
<CustomField>
    <fullName>File_Size__c</fullName>
    <label>File Size</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project/dropbox/main/default/objects/DropBoxFile__c/fields/FileExtension__c.field-meta.xml
<CustomField>
    <fullName>FileExtension__c</fullName>
    <label>FileExtension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

project/dropbox/main/default/objects/DropBoxFile__c/fields/Is_Folder__c.field-meta.xml
<CustomField>
    <fullName>Is_Folder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Folder</label>
    <type>Checkbox</type>
</CustomField>

project/dropbox/main/default/objects/DropBoxFile__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+ RecordId__c , &apos;Parent Record&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ParentId</label>
    <type>Text</type>
</CustomField>

project/dropbox/main/default/objects/DropBoxFile__c/fields/ServerUrl__c.field-meta.xml
<CustomField>
    <fullName>ServerUrl__c</fullName>
    <label>ServerUrl</label>
    <type>Url</type>
</CustomField>

project/dropbox/main/default/classes/FileManagerController.cls
public with sharing class FileManagerController {
    /**
     * @description Get stored files from DropBoxFile__c object for the specified account
     * @param accountId The ID of the account
     * @return List<DropBoxFile__c> List of stored files
     */
    @AuraEnabled(cacheable=true)
    public static List<DropBoxFile__c> getStoredFiles(String accountId) {
        try {
            return [
                SELECT Id, Name, ServerUrl__c, RecordId__c, FileExtension__c, ParentId__c,
                Dropbox_File_Id__c, Dropbox_Path__c, File_Size__c, Content_Document_Id__c,
                Is_Folder__c 
                FROM DropBoxFile__c
                WHERE RecordId__c = :accountId
                ORDER BY Name ASC
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving stored files: ' + e.getMessage());
        }
    }
}