force-app/main/default/objects/Media__c/Media__c.object-meta.xml
<CustomObject>
    <label>Media</label>
    <nameField>
        <displayFormat>MEDIA-{00000}</displayFormat>
        <label>Media ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Media__c/fields/ButtonText__c.field-meta.xml
<CustomField>
    <fullName>ButtonText__c</fullName>
    <label>Button Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media__c/fields/ButtonUrl__c.field-meta.xml
<CustomField>
    <fullName>ButtonUrl__c</fullName>
    <label>Button Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Media__c/fields/Heading__c.field-meta.xml
<CustomField>
    <fullName>Heading__c</fullName>
    <label>Heading</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Media__c/fields/Media_Type__c.field-meta.xml
<CustomField>
    <fullName>Media_Type__c</fullName>
    <label>Media Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Course Detail</fullName>
            </value>
            <value>
                <fullName>Course List</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Booking Confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Media__c/fields/PublicUrl__c.field-meta.xml
<CustomField>
    <fullName>PublicUrl__c</fullName>
    <label>Public Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Media__c/fields/Subheading__c.field-meta.xml
<CustomField>
    <fullName>Subheading__c</fullName>
    <label>Subheading</label>
    <length>768</length>
    <type>LongTextArea</type>
</CustomField>

web/main/default/classes/MediaService.cls
/**
 * @description       : 
 * @author            : Amit Singh - PantherSchools
 * @group             : 
 * @last modified on  : 06-14-2024
 * @last modified by  : Amit Singh - PantherSchools
**/
public without sharing class MediaService {
    
    @AuraEnabled(cacheable=true)
    public static List<sObject> fetch(String typex){
        try {
            return [SELECT Id, Subheading__c, Heading__c, Media_Type__c, PublicUrl__c, ButtonText__c, ButtonUrl__c FROM Media__c WHERE Media_Type__c = :typex ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}