force-app/main/default/objects/Agent__c/Agent__c.object-meta.xml
<CustomObject>
    <label>Agent</label>
    <nameField>
        <label>Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agent__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agent?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agent__c/fields/ZendeskId__c.field-meta.xml
<CustomField>
    <fullName>ZendeskId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Agent__c.Agent__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Agent__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Zendesk_Ticket_Id__c.field-meta.xml
<CustomField>
    <fullName>Zendesk_Ticket_Id__c</fullName>
    <label>Zendesk Ticket Id</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/ZendeskErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ZendeskErrorMessage__c</fullName>
    <label>Zendesk Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

assignments/zendesk/main/default/classes/Assignment_CaseTriggerHandler.cls
/**
 * @description       : 
 * @author            : Amit Singh - PantherSchools
 * @group             : 
 * @last modified on  : 06-08-2024
 * @last modified by  : Amit Singh - PantherSchools
**/
public with sharing class Assignment_CaseTriggerHandler {

    @future(callout = true)
    public static void syncWithZendesk(String caseRecordId){
        Case newRecord = [SELECT Id, CaseNumber, Subject, Description, ContactId, Priority,
                                Contact.Name, Contact.Email, SuppliedEmail, SuppliedName,
                                Agent__c, Agent__r.ZendeskId__c
                            FROM
                                Case 
                            WHERE 
                                Id =: caseRecordId
                        ];

        Assignment_ZendeskUtils.TicektWrapper wrapper = new Assignment_ZendeskUtils.TicektWrapper();
        wrapper.body = newRecord.Description;
        wrapper.subject = newRecord.Subject;
        wrapper.priority = newRecord.Priority.toLowerCase();
        wrapper.name = newRecord.Contact.Name ?? newRecord.SuppliedName;
        wrapper.email = newRecord.Contact.Email ?? newRecord.SuppliedEmail;
        wrapper.agentId = newRecord.Agent__r.ZendeskId__c ?? null;

        HttpResponse httpRes = Assignment_ZendeskUtils.createTicket(wrapper);

        if(httpRes?.getStatusCode() == 201 || httpRes?.getStatusCode() == 200){
            String responseBody = httpRes.getBody();
            Assignment_ZendeskTicketWrapper ticket = (Assignment_ZendeskTicketWrapper)JSON.deserialize(responseBody, Assignment_ZendeskTicketWrapper.class);
            if(ticket?.ticket?.id != null){
                newRecord.Zendesk_Ticket_Id__c = Integer.valueOf(ticket.ticket.id);
                update newRecord;
            }
        }else{
            System.debug(' Error Occured While Creating Records '+ httpRes?.getBody() );
            newRecord.ZendeskErrorMessage__c = httpRes?.getBody();
            update newRecord;
        }
    }

}